name: "Build and Deploy"
on:
  push:
    branches:
      - main
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Setup node"
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: "Build"
      run: |
        yarn
        yarn build

    - name: "Create CNAME file"
      run: echo "coordinates.popp.xyz" >> dist/CNAME

    - name: "Stage Files"
      run: git add -f dist

    - name: "Commit files"
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git commit -m "Build for deploy"

    - name: "Publish"
      run: |
        git push origin `git subtree split --prefix dist main`:gh-pages --force
